name: Caching with npm
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: <WorkFlow Name>
        uses: athul/telewire@master
        if: always()
        with:
          chat: ${{ secrets.chat }}
          token: ${{ secrets.token }}
          status: ${{ job.status }}
